// Code generated by "stringer -type=Group"; DO NOT EDIT.

package english

import "strconv"

const _Group_name = "VerbNounAdjectiveInjection"

var _Group_index = [...]uint8{0, 4, 8, 17, 26}

func (i Group) String() string {
	if i < 0 || i >= Group(len(_Group_index)-1) {
		return "Group(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Group_name[_Group_index[i]:_Group_index[i+1]]
}
